import { Geist, Geist_Mono } from "next/font/google";
import StyledComponentsRegistry from "./lib/resistry";
import "./globals.css";
import '../public/css/common.css';
import NavBar from "./components/navigation/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "bookdam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StyledComponentsRegistry>
          {children}
          <NavBar />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
