import { Geist, Geist_Mono } from "next/font/google";
import StyledComponentsRegistry from "./lib/resistry";
import "./globals.css";
import '../public/css/common.css';
import ClientRoot from "./components/ClientRoot";
import NavBar from "./components/navigation/NavBar";
import createClient from "@/utils/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "bookdam",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { session, profile } = await createClient()
  console.log('session:🚀', profile)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StyledComponentsRegistry>
          <ClientRoot initialSession={session} initialProfile={profile}>
            {children}
            <NavBar />
          </ClientRoot>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
