import { Geist, Geist_Mono } from "next/font/google";
import StyledComponentsRegistry from "./lib/resistry";
import "./globals.css";
import ClientRoot from "./components/ClientRoot";
import NavBar from "./components/navigation/NavBar";
import createClient from "@/utils/supabase/server";
import { AppleSDGothicNeo } from "@/public/fonts/fonts";
import { ToastContainer } from "react-toastify";
import Toast from "./components/modal/Toast";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "bookdam",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const {
    session, profile,
    reviews, memo, books, log, wish, settings
  } = await createClient()
  return (
    <html lang="en" className={AppleSDGothicNeo.className}>
      <body>
        <div className="relative width-[100%] shadow-2xl overflow-x-hidden bg-[var(--color_white)]">
          <StyledComponentsRegistry>
            <ClientRoot
            initialSession={session}
            initialProfile={profile}
            initialReview={reviews}
            initialMemo={memo}
            initialBooks={books}
            initialLog={log}
            initialWish={wish}
            initialSettings={settings}
            >
              <ToastContainer limit={3} />
              <Toast />
              <Header />
              {children}
              <Footer />
              <NavBar />
            </ClientRoot>
          </StyledComponentsRegistry>
        </div>
      </body>
    </html>
  );
}
